import type { DefaultTheme } from "vitepress";

export const baseSidebarSection: DefaultTheme.SidebarItem[] = [
  {
    text: "Base",
    collapsed: false,
    items: [
      // { text: "前端知识图谱", link: "/workspace/Js/frontend-map" },
      { text: "技术清单", link: "/workspace/Js/home" },
      { text: "Array的方法简单整理", link: "/workspace/Js/array" },
      { text: "Object的方法简单整理", link: "/workspace/Js/object" },
      { text: "String的方法简单整理", link: "/workspace/Js/string" },
      { text: "Date时间", link: "/workspace/Js/date" },
      { text: "RegExp正则", link: "/workspace/Js/reg" },
      { text: "CSS使用锦囊", link: "/workspace/Css/css" },
      // { text: "九宫格实现", link: "/workspace/Css/lattice" },
      { text: "自定义事件", link: "/workspace/Js/dispatchEvent" },
      { text: "for in和for of区别", link: "/workspace/Js/for-in-for-of" },
      { text: "ES6-新增特性一览", link: "/workspace/Js/es6" },
      { text: "Event-Loop", link: "/workspace/Js/eventloop" },
      { text: "Promise & async", link: "/workspace/Js/promise" },
      { text: "Web Worker", link: "/workspace/Js/webWorker" },
      { text: "WebSocket & socket.io", link: "/workspace/Js/socket" },
      { text: "shell & ssh", link: "/workspace/Project/linux" },
      { text: "yarn & npm", link: "/workspace/Project/yarn" },
      { text: "堆内存 & 栈内存", link: "/workspace/Js/heap_stack" },
      { text: "Fetch和Axios的区别", link: "/workspace/Js/xhr" },
      { text: "JS设计模式探索", link: "/workspace/Js/design-pattern" },
      { text: "浏览器渲染原理", link: "/workspace/Js/http-base" },
      { text: "原型与原型链", link: "/workspace/Js/extends" },
      { text: "leetCode", link: "/workspace/Project/leetcode" },
    ],
  },
  {
    text: "Project",
    collapsed: true,
    items: [
      { text: "用到的方法", link: "/workspace/Project/method" },
      { text: "简易封装Cookie", link: "/workspace/Project/cookie" },
      { text: "toFixed方法的bug", link: "/workspace/Project/toFixed" },
      { text: "实现JS复制内容到剪贴板", link: "/workspace/Project/copy" },
      { text: "全屏实现方案", link: "/workspace/Project/screenfull" },
      { text: "base64上传七云获取key", link: "/workspace/Project/qiyunniu" },
      { text: "聊一聊前端换肤", link: "/workspace/Js/theme" },
      { text: "JS添加水印功能", link: "/workspace/Js/water-mask" },
      { text: "Axios 获取文件流导出 excel 表格", link: "/workspace/Js/export" },
      { text: "首屏性能优化", link: "/workspace/Project/perf-opt" },
    ],
  },
];
