import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"项目目录","description":"","frontmatter":{},"headers":[],"relativePath":"workspace/Frame/taro/toc.md","filePath":"workspace/Frame/taro/toc.md","lastUpdated":1715005148000}');
const _sfc_main = { name: "workspace/Frame/taro/toc.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="项目目录" tabindex="-1">项目目录 <a class="header-anchor" href="#项目目录" aria-label="Permalink to &quot;项目目录&quot;">​</a></h1><p><strong>以Taro为栗子</strong></p><div class="language-bash line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki one-dark-pro vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">├─config</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">   --</span><span style="${ssrRenderStyle({ "color": "#98C379" })}"> 配置文件</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">插件等</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">)  </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">      dev.js</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">  --开发项目配置</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">      index.js</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">  --适用于开发和生产</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">      prod.js</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">   --生产项目配置</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">      template.js</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">  --node写的文件模板，直接构建</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">├─src</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">  </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  │--app.tsx</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">  --项目入口文件</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  │--app.scss</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">  --</span><span style="${ssrRenderStyle({ "color": "#98C379" })}"> 全局样式文件</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">会自动引入</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">)  </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  │--global.tsx</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">  --</span><span style="${ssrRenderStyle({ "color": "#98C379" })}"> 项目全局引入</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">可在里面引入一些全局用到的包</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">)  </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  ├─public</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">  --资源文件</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">  </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  ├─components</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">    --系统通用组件</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  ├─layouts</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">   --</span><span style="${ssrRenderStyle({ "color": "#98C379" })}"> 布局文件夹</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">   </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  ├─models</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">  --全局model(</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">非全局的不能放到这个下面</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">)</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">  </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  ├─pages</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">  --业务相关页面</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">  </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">  |</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">业务中用到的页面建议按模块划分，注意大小写保持一致</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">  </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">  |</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">如果用到model，注意增加models文件夹</span><span style="${ssrRenderStyle({ "color": "#98C379" })}"> model的namespace得全局唯一，建议按文件夹层级命名</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">  </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">  |</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  ├─service</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">  --</span><span style="${ssrRenderStyle({ "color": "#98C379" })}"> 服务方法</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  │</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">      api.ts</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> --request的二次封装</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  │</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">      global.service.ts</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">   --全局用到的接口</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  │</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">      config.default.ts</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">  --状态码和生产开发域名的配置</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  ├─dev</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">  --开发专用的一些快捷方式</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  ├─bases</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">  --</span><span style="${ssrRenderStyle({ "color": "#98C379" })}"> 底层框架的封装</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  ├─types</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">  --系统中用到的一些类型定义</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  ├─utils</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">  --辅助方法</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  │</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">      lodash.ts</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">  --权限辅助方法</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">  </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  │</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">      storage.ts</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">  --本地存储的一些方法</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  │</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">      index.ts</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">  --通用辅助方法(</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">导入的时候</span><span style="${ssrRenderStyle({ "color": "#98C379" })}"> import</span><span style="${ssrRenderStyle({ "color": "#98C379" })}"> {xx}</span><span style="${ssrRenderStyle({ "color": "#98C379" })}"> from</span><span style="${ssrRenderStyle({ "color": "#98C379" })}"> &#39;@/utils&#39;即可</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">)</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">  </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  │</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">      docs.ts</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">   --一些状态展示用的方法</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  │</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">      constants.ts</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">  --定义的一些常量</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  │</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">      regexp.ts</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> --正则相关辅助方法</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">   </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  │</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">      router.ts</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> --路由相关的方法</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">│</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">  └─</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">└─project.config.json</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> --微信小程序的配置</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">└─project.swan.json</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> --百度智能小程序</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">└─project.tt.json</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> --头条小程序的配置</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">└─project.quickapp.json</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> --快应用</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">└─project.qq.json</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> --QQ小程序</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br></div></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("workspace/Frame/taro/toc.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const toc = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  toc as default
};
