import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"自定义事件","description":"","frontmatter":{},"headers":[],"relativePath":"workspace/Js/dispatchEvent.md","filePath":"workspace/Js/dispatchEvent.md","lastUpdated":1713942612000}');
const _sfc_main = { name: "workspace/Js/dispatchEvent.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="自定义事件" tabindex="-1">自定义事件 <a class="header-anchor" href="#自定义事件" aria-label="Permalink to &quot;自定义事件&quot;">​</a></h1><h2 id="dispatchevent" tabindex="-1">dispatchEvent <a class="header-anchor" href="#dispatchevent" aria-label="Permalink to &quot;dispatchEvent&quot;">​</a></h2><p><strong>已废弃</strong></p><p><a href="https://developer.mozilla.org/zh-CN/docs/Web/API/Event/Event" target="_blank" rel="noreferrer">initEvent</a></p><h2 id="createevent" tabindex="-1">createEvent() <a class="header-anchor" href="#createevent" aria-label="Permalink to &quot;createEvent()&quot;">​</a></h2><p><code>createEvent()</code>方法返回新创建的Event对象，支持一个参数，表示事件类型，具体见下表：</p><table><thead><tr><th>参数</th><th>事件接口</th><th>初始化方法</th></tr></thead><tbody><tr><td>HTMLEvents</td><td>HTMLEvent</td><td>initEvent()</td></tr><tr><td>MouseEvents</td><td>MouseEvent</td><td>initMouseEvent()</td></tr><tr><td>UIEvents</td><td>UIEvent</td><td>initUIEvent()</td></tr></tbody></table><h2 id="initevent" tabindex="-1">initEvent() <a class="header-anchor" href="#initevent" aria-label="Permalink to &quot;initEvent()&quot;">​</a></h2><p><code>initEvent()</code>方法用于初始化通过<code>DocumentEvent</code>接口创建的Event的值。</p><p>支持三个参数：<code>initEvent(eventName, canBubble, preventDefault)</code> 分别表示：</p><ul><li>事件名称</li><li>是否可以冒泡</li><li>是否阻止事件的默认操作</li></ul><h2 id="dispatchevent-1" tabindex="-1">dispatchEvent() <a class="header-anchor" href="#dispatchevent-1" aria-label="Permalink to &quot;dispatchEvent()&quot;">​</a></h2><p><code>dispatchEvent()</code>就是触发执行了，<code>dom.dispatchEvent(eventObject)</code> 参数<code>eventObject</code>表示事件对象，是<code>createEvent()</code>方法返回的创建的<code>Event</code>对象。</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki one-dark-pro vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">/*TODO: 基于浏览器原生事件做通信*/</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">// 创建</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">window</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">evt</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}"> =</span><span style="${ssrRenderStyle({ "color": "#E5C07B" })}"> document</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">createEvent</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;HTMLEvents&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">);</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">// 初始化</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">window</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">evt</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">initEvent</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;handleData&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">false</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">false</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">);</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">// 监听</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">document</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">addEventListener</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&#39;handleData&#39;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">this</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">handelData</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">false</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">);</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">// 触发事件</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">document</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">dispatchEvent</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">ev</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">);</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><h2 id="event-单向" tabindex="-1">Event (单向) <a class="header-anchor" href="#event-单向" aria-label="Permalink to &quot;Event (单向)&quot;">​</a></h2><p><a href="https://developer.mozilla.org/zh-CN/docs/Web/API/Event/Event" target="_blank" rel="noreferrer">Event</a></p><p><strong>语法</strong></p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki one-dark-pro vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">event</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}"> =</span><span style="${ssrRenderStyle({ "color": "#C678DD" })}"> new</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}"> Event</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">typeArg</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">eventInit</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">);</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}">1.</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> typeArg</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> 事件名称</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}">2.</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> eventInit</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#98C379" })}">  &quot;bubbles&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">，</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">可选</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> 默认值为</span><span style="${ssrRenderStyle({ "color": "#98C379" })}"> \`false\`</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">，</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">表示该事件是否冒泡</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">。</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#98C379" })}">  &quot;cancelable&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">，</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">可选</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> 默认值为</span><span style="${ssrRenderStyle({ "color": "#98C379" })}"> \`false\`</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">， </span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">表示该事件能否被取消</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">。</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#98C379" })}">  &quot;composed&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">，</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">可选</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> 默认值为</span><span style="${ssrRenderStyle({ "color": "#98C379" })}"> \`false\`</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">，</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">指示事件是否会在影子DOM根节点之外触发侦听器</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">。</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#C678DD" })}">const</span><span style="${ssrRenderStyle({ "color": "#E5C07B" })}"> ev</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}"> =</span><span style="${ssrRenderStyle({ "color": "#C678DD" })}"> new</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}"> Event</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;look&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, {</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;bubbles&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">:</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">true</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;cancelable&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">:</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">false</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">});</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">// 监听事件</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">document</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">addEventListener</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&#39;look&#39;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#C678DD" })}">function</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> (</span><span style="${ssrRenderStyle({ "color": "#E06C75", "font-style": "italic" })}">e</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">) { ... }, </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">false</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">);</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">// 触发事件</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">document</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">dispatchEvent</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">ev</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">);</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">// 事件可以在任何元素触发，不仅仅是document</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">myDiv</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">dispatchEvent</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">ev</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">);</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br></div></div><h2 id="customevent-多向" tabindex="-1">CustomEvent（多向） <a class="header-anchor" href="#customevent-多向" aria-label="Permalink to &quot;CustomEvent（多向）&quot;">​</a></h2><p><a href="https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent" target="_blank" rel="noreferrer">CustomEvent</a></p><p><code>CustomEvent</code> 可以创建一个更高度自定义事件，还可以附带一些数据，具体用法如下：</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki one-dark-pro vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#C678DD" })}">var</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> myEvent</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}"> =</span><span style="${ssrRenderStyle({ "color": "#C678DD" })}"> new</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}"> CustomEvent</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">eventname</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">options</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">);</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">其中</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> options</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> 可以是</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">：</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">  detail</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    ...</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">  }, </span><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">// 初始化事件时传递的所有数据。</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">  bubbles</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">true</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">,    </span><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">//是否冒泡</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">  cancelable</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">false</span><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}"> //是否取消默认事件</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki one-dark-pro vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">// 父应用 </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#C678DD" })}">export</span><span style="${ssrRenderStyle({ "color": "#C678DD" })}"> default</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">   mounted</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#C678DD" })}">      function</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}"> createEvent</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#E06C75", "font-style": "italic" })}">params</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#E06C75", "font-style": "italic" })}">eventName</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}"> =</span><span style="${ssrRenderStyle({ "color": "#98C379" })}"> &#39;look&#39;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">        // 数据必须挂载到detail上</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#C678DD" })}">        return</span><span style="${ssrRenderStyle({ "color": "#C678DD" })}"> new</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}"> CustomEvent</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">eventName</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, {</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">detail</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">params</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">});</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">      }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">      // 初始化</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">      window</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">cEvt</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}"> =</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}"> createEvent</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">({</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">handelData</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">this</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">handelData</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">});</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">    methods</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">      handelData</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(...</span><span style="${ssrRenderStyle({ "color": "#E06C75", "font-style": "italic" })}">opt</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">        this</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">ary</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">push</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(...</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">opt</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">        // 去重</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">        this</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">ary</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}"> =</span><span style="${ssrRenderStyle({ "color": "#E5C07B" })}"> _</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">uniqWith</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">this</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">ary</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">_</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">isEqual</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">);</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#C678DD" })}">        return</span><span style="${ssrRenderStyle({ "color": "#E5C07B" })}"> this</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">ary</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">      }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">// 子应用</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#C678DD" })}">export</span><span style="${ssrRenderStyle({ "color": "#C678DD" })}"> default</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">   methods</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">     queryData</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">({</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">detail</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: {</span><span style="${ssrRenderStyle({ "color": "#E06C75", "font-style": "italic" })}">handelData</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}}) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">       // 返回当前传入的值</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#C678DD" })}">       const</span><span style="${ssrRenderStyle({ "color": "#E5C07B" })}"> data</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}"> =</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">  handelData</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">({</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">ary</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: [</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">1</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">2</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">3</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">4</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">], </span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">msg</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&#39;子传父&#39;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">});</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">     },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">     dispatchData</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">       // 子应用触发当前函数</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">       document</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">addEventListener</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&#39;look&#39;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">this</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">queryData</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">);</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">       // 发起事件</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">       document</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">dispatchEvent</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">window</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">cEvt</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">);</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">     },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">   },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">   mounted</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">      // 移除事件监听器。</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">      this</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">$once</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&#39;hook:beforeDestroy&#39;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, () </span><span style="${ssrRenderStyle({ "color": "#C678DD" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">        document</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">removeEventListener</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&#39;look&#39;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">this</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">queryData</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">);</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">      })</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">   },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br></div></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("workspace/Js/dispatchEvent.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const dispatchEvent = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  dispatchEvent as default
};
