import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"CSS九宫格布局实现","description":"","frontmatter":{},"headers":[],"relativePath":"workspace/Css/lattice.md","filePath":"workspace/Css/lattice.md","lastUpdated":1714231776000}');
const _sfc_main = { name: "workspace/Css/lattice.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="css九宫格布局实现" tabindex="-1">CSS九宫格布局实现 <a class="header-anchor" href="#css九宫格布局实现" aria-label="Permalink to &quot;CSS九宫格布局实现&quot;">​</a></h1><p><strong>基本的布局</strong></p><div class="language-html line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">html</span><pre class="shiki one-dark-pro vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&lt;!</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">DOCTYPE</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> html</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">html</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">head</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    &lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">meta</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> charset</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">=</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;UTF-8&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    &lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">meta</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> name</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">=</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;viewport&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}">          content</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">=</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;width=device-width,user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1,viewport-fit=cover&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    &lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">title</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;&lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">title</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    &lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">style</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}">        .box</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">            background: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">#e4f7fd61</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">            border: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">2</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> solid</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> #0786ada1</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">            border-radius: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">8</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">        }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">        ul</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">            padding: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">0</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">            margin: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">0</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">        }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}">        .box</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">            list-style: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">none</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">            text-align: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">center</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">            line-height: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">200</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">            background: </span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}">rgba</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">146</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">203</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">230</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">0.65</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">);</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">            border-radius: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">8</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">        }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    &lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">style</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">head</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">body</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">div</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> class</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">=</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;box&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    &lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">ul</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> class</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">=</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;flex grid&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">        &lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;1&lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">        &lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;2&lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">        &lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;3&lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">        &lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;4&lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">        &lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;5&lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">        &lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;6&lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">        &lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;7&lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">        &lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;8&lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">        &lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;9&lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    &lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">ul</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">div</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">body</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">html</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br><span class="line-number">43</span><br></div></div><h3 id="margin负值实现" tabindex="-1">margin负值实现 <a class="header-anchor" href="#margin负值实现" aria-label="Permalink to &quot;margin负值实现&quot;">​</a></h3><ul><li>最外层的包裹元素等于：li宽度<em>3+li右间距</em>2</li><li>子盒子左浮动，margin-left margin-bottom间距为20px</li><li>父盒子的margin-bottom和margin-top的的间距为-20px,消除子盒子代理的移动</li><li>父盒子消除浮动</li></ul><div class="language-css line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">css</span><pre class="shiki one-dark-pro vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}">.box</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    width: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">940</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">ul</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    margin-right: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">-20</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    margin-bottom: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">-20</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;  </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">ul</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}">:after</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    content: </span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&#39;&#39;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    display: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">block</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    height: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">0</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    width: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">0</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    clear: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">both</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    visibility: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">hidden</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}">.box</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    float: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">left</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    width: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">300</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    height: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">200</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    margin-right: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">20</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    margin-bottom: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">20</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br></div></div><h3 id="nth-child" tabindex="-1">nth-child <a class="header-anchor" href="#nth-child" aria-label="Permalink to &quot;nth-child&quot;">​</a></h3><p>跟上面的那种方法类似，就是把父盒子的移动换成了指定的子盒子移动</p><p>但是这回出现一个问题就是最下的一层盒子个数不确定所以margin-bottom,就没办法正确的设置 所以就会用到css的级联使用，方法看如下的代码：</p><div class="language-css line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">css</span><pre class="shiki one-dark-pro vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#C678DD" })}">...</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">  // </span><span style="${ssrRenderStyle({ "color": "#C678DD" })}">代码跟上面的一致，去除UI部分</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}">.box</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> li</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}">:nth-child</span><span style="${ssrRenderStyle({ "color": "#C678DD" })}">(</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">3n</span><span style="${ssrRenderStyle({ "color": "#C678DD" })}">)</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    margin-right: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">0</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}">.box</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> li</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}">:nth-child</span><span style="${ssrRenderStyle({ "color": "#C678DD" })}">(</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">3n+1</span><span style="${ssrRenderStyle({ "color": "#C678DD" })}">)</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}">:nth-last-child</span><span style="${ssrRenderStyle({ "color": "#C678DD" })}">(</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">-n+3</span><span style="${ssrRenderStyle({ "color": "#C678DD" })}">)</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">,</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> .box</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> li</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}">:nth-child</span><span style="${ssrRenderStyle({ "color": "#C678DD" })}">(</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">3n+1</span><span style="${ssrRenderStyle({ "color": "#C678DD" })}">)</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}">:nth-last-child</span><span style="${ssrRenderStyle({ "color": "#C678DD" })}">(</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">-n+3</span><span style="${ssrRenderStyle({ "color": "#C678DD" })}">) </span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">~</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    margin-bottom: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">0</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">// </span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">li</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}">:nth-last-child</span><span style="${ssrRenderStyle({ "color": "#C678DD" })}">(</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">-n+3</span><span style="${ssrRenderStyle({ "color": "#C678DD" })}">)</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div><h3 id="grid布局" tabindex="-1">grid布局 <a class="header-anchor" href="#grid布局" aria-label="Permalink to &quot;grid布局&quot;">​</a></h3><div class="language-css line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">css</span><pre class="shiki one-dark-pro vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> .grid</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    display: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">grid</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    grid-template-rows: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">100</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> 100</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> 100</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    grid-template-columns: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">100</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> 100</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> 100</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}">.grid</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> &gt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    margin-top: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">4</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    margin-left: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">4</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    box-sizing: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">border-box</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    list-style: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">none</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    line-height: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">100</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    text-align: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">center</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    border: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">4</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> solid</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> #ccc</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    background: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">#6a8bad</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}">.grid</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> &gt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> li</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}">:hover</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    border-color: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">red</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    position: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">relative</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    transition: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">all</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> 500</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">ms</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">    /*z-index:-2;*/</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br></div></div><p>这里有一个地方需要注意，就是不要再给li子项设置宽度和高度。 该grid布局中，也可以在hover时添加z-index:2;来提高叠加等级,不然没办法展示全部</p><h3 id="flex布局" tabindex="-1">flex布局 <a class="header-anchor" href="#flex布局" aria-label="Permalink to &quot;flex布局&quot;">​</a></h3><div class="language-css line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">css</span><pre class="shiki one-dark-pro vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}">.flex</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    display: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">flex</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    width: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">312</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    flex-wrap: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">wrap</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    margin: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">-4</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> 0</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> 0</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> -4</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}">.flex</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> &gt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> li</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    box-sizing: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">border-box</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    height: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">100</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    width: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">100</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    margin-left: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">4</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    margin-top: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">4</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    line-height: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">100</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">px</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    text-align: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">center</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    list-style: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">none</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    background: </span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}">rgba</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">146</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">203</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">230</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">0.65</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">);</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}">.flex</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> &gt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> li</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}">:hover</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    background: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">red</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    position: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">relative</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">    /*z-index:2;*/</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br></div></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("workspace/Css/lattice.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const lattice = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  lattice as default
};
