import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"snowpack","description":"","frontmatter":{},"headers":[],"relativePath":"workspace/Snowpack/base.md","filePath":"workspace/Snowpack/base.md","lastUpdated":1715005148000}');
const _sfc_main = { name: "workspace/Snowpack/base.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="snowpack" tabindex="-1">snowpack <a class="header-anchor" href="#snowpack" aria-label="Permalink to &quot;snowpack&quot;">​</a></h1><p><a href="https://github.com/snowpackjs/snowpack" target="_blank" rel="noreferrer">github 18k</a></p><h2 id="放弃-webpack-使用-snowpack-构建-vue2" tabindex="-1">放弃 webpack 使用 snowpack 构建 vue2 <a class="header-anchor" href="#放弃-webpack-使用-snowpack-构建-vue2" aria-label="Permalink to &quot;放弃 webpack 使用 snowpack 构建 vue2&quot;">​</a></h2><p>vue不建议使用snowpack ，直接使用vite</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki one-dark-pro vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#C678DD" })}">const</span><span style="${ssrRenderStyle({ "color": "#E5C07B" })}"> CompressionWebpackPlugin</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}"> =</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}"> require</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;compression-webpack-plugin&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">);</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#C678DD" })}">const</span><span style="${ssrRenderStyle({ "color": "#E5C07B" })}"> ProgressBarPlugin</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}"> =</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}"> require</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;progress-bar-webpack-plugin&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">);</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">module</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">exports</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}"> =</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">  mode</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;development&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">  mount</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">    public</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;/&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">    src</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;/_build_&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">  plugins</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#98C379" })}">      &quot;@snowpack/plugin-webpack&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">      {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">        manifest</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">true</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">        extendConfig</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: (</span><span style="${ssrRenderStyle({ "color": "#E06C75", "font-style": "italic" })}">config</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">) </span><span style="${ssrRenderStyle({ "color": "#C678DD" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">          config</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">plugins</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">push</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">            // 生产模式  下面 plugins 为了测试</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#C678DD" })}">            new</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}"> ProgressBarPlugin</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#C678DD" })}">            new</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}"> CompressionWebpackPlugin</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">({</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">              filename</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;[path].gz[query]&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">// 压缩后的文件策略</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">              algorithm</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;gzip&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">// 压缩方式</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">              test</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">:</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> /</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}">\\.</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">(js</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">|</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">css</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">|</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">html</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">|</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">svg)</span><span style="${ssrRenderStyle({ "color": "#C678DD" })}">$</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">/</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">// 可设置需要压缩的文件类型</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">              threshold</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">10240</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">// 大于 10 kb 的文件启用压缩</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">              minRatio</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">0.8</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">// 压缩比率大于等于0.8时不进行压缩</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">              deleteOriginalpublic</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">false</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">// 是否删除压缩前的文件，默认false</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">            }),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">          );</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">          console</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#61AFEF" })}">log</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">(</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">1212</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">config</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">);</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#C678DD" })}">          return</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}"> config</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">        },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">      },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    ],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">    // &quot;@snowpack/plugin-vue&quot;, // 仅支持 vue3</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#98C379" })}">    &quot;snowpack-vue2-plugin&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#98C379" })}">    &quot;@snowpack/plugin-sass&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#98C379" })}">    &quot;@snowpack/plugin-dotenv&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">// 环境变量</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">  ],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">  devOptions</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">    port</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">9988</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">  env</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    ...</span><span style="${ssrRenderStyle({ "color": "#E5C07B" })}">process</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">env</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">, </span><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">// 环境变量</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">    API_URL</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;api.google.com&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">  alias</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: { </span><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">// 别名</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">    vue</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;vue/dist/vue.esm.js&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">    src</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;./src&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#98C379" })}">    &quot;@&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;./src&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E06C75" })}">    public</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">: </span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;./src&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">};</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br><span class="line-number">43</span><br><span class="line-number">44</span><br><span class="line-number">45</span><br><span class="line-number">46</span><br><span class="line-number">47</span><br><span class="line-number">48</span><br><span class="line-number">49</span><br><span class="line-number">50</span><br><span class="line-number">51</span><br></div></div><p>打包后的文件格式</p><div class="language-tex line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">tex</span><pre class="shiki one-dark-pro vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">├── _build_ // 这里是开发使用  直接使用esm</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│   ├── app.vue.css</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│   ├── app.vue.css.proxy.js</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│   ├── app.vue.js</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│   ├── public // 静态资源要使用import导入才能用</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│   │   ├── css</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│   │   │   ├── base.css</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│   │   │   └── common.css</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│   │   └── images</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│   │       ├── logo.svg</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│   │       └── logo.svg.proxy.js </span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│   └── main.js</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">├── _snowpack // _snowpack 会识别当前引入的包，打包到一块</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│   ├── env.js</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│   └── pkg</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│       ├── import-map.json</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│       └── vue</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│           └── dist</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│               └── vue.esm.js</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">| // 下面是生产模式用的</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">├── asset-manifest.json</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">├── asse─ asse打包ao├─ao─ asse─ asse打包ts</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│   └── logo-0bd12d7f66941cb709a7916ed3711b83.svg</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">├── css</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│   └── styles.54be0dbcaf3903e9ecf0.css</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">├── favicon.ico</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">├── index.html</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">├── js</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│   ├── main.c7209184f49f325aa215.js</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│   ├── styles.8c0579408b74c01eb83f.js</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">│   └── webpack-runtime.0ec3dfa59e6510ed107b.js</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">└── logo.svg</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br></div></div><p>_ snowpack _ 文件夹里面包含的是snowpack脚手架自身包含的：其中env.js 是环境变量的配置文件，文件带hmr的项目热更新的配置文件。 _ dist _ 里面包含的页面应用到的js,css 等其他资源文件，就是app.vue里面的东西。</p><h2 id="不足" tabindex="-1">不足 <a class="header-anchor" href="#不足" aria-label="Permalink to &quot;不足&quot;">​</a></h2><ul><li><p>vue2热加载不兼容，官方非常微妙的表明了一点<em>Vue（仅适用于HMR）</em>，这意味着Vue不支持<em>快速刷新</em>（仅完全重新加载）</p></li><li><p>使用了 ESM 不支持require，报错 <code>require is not defined</code></p></li><li><p>页面报错后 hmr就会大概率失效</p></li><li><p>引入ui 库 会报出静态资源404的问题</p></li></ul><h2 id="参考文档" tabindex="-1">参考文档 <a class="header-anchor" href="#参考文档" aria-label="Permalink to &quot;参考文档&quot;">​</a></h2><p><a href="https://www.snowpack.dev/reference/configuration#mode" target="_blank" rel="noreferrer">文档 需翻墙</a></p><p><a href="https://www.snowpack.dev/concepts/hot-module-replacement" target="_blank" rel="noreferrer">hmr 暂时没找到兼容vue2的 hmr</a></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("workspace/Snowpack/base.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const base = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  base as default
};
