import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"清除浮动的最常用的几种方法","description":"","frontmatter":{},"headers":[],"relativePath":"workspace/Css/clearfix.md","filePath":"workspace/Css/clearfix.md","lastUpdated":1714231776000}');
const _sfc_main = { name: "workspace/Css/clearfix.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="清除浮动的最常用的几种方法" tabindex="-1">清除浮动的最常用的几种方法 <a class="header-anchor" href="#清除浮动的最常用的几种方法" aria-label="Permalink to &quot;清除浮动的最常用的几种方法&quot;">​</a></h1><p><strong>为什么要清除浮动？</strong></p><p>清除浮动主要是为了解决，父元素因为子级元素浮动引起的内部高度为0的问题</p><h2 id="额外标签法" tabindex="-1">额外标签法 <a class="header-anchor" href="#额外标签法" aria-label="Permalink to &quot;额外标签法&quot;">​</a></h2><p>在最后一个浮动标签后，新加一个标签，给其设置clear：both；（不推荐）</p><div class="language-html line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">html</span><pre class="shiki one-dark-pro vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.clear{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    clear:both;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">div</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> class</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">=</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;box&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    &lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">div</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;&lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">div</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    &lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">div</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;&lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">div</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    &lt;</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">div</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}"> class</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">=</span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;clear&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;额外标签法&lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">div</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&lt;/</span><span style="${ssrRenderStyle({ "color": "#E06C75" })}">div</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">&gt;</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><h2 id="父级添加overflow属性" tabindex="-1">父级添加overflow属性 <a class="header-anchor" href="#父级添加overflow属性" aria-label="Permalink to &quot;父级添加overflow属性&quot;">​</a></h2><p>通过触发BFC的方式，实现清楚浮动效果。</p><div class="language-html line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">html</span><pre class="shiki one-dark-pro vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">.box{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">   overflow: hidden;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><p><strong>缺点</strong>：内容增多的时候容易造成不会自动换行导致内容被隐藏掉，无法显示要溢出的元素,局限性太大</p><h2 id="使用after伪元素清除浮动" tabindex="-1">使用after伪元素清除浮动 ** <a class="header-anchor" href="#使用after伪元素清除浮动" aria-label="Permalink to &quot;使用after伪元素清除浮动 **&quot;">​</a></h2><div class="language-css line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">css</span><pre class="shiki one-dark-pro vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}">.clearfix</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}">:after</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">{</span><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">/*伪元素是行内元素 正常浏览器清除浮动方法*/</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    content: </span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    display: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">block</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    height: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">0</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    clear:</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">both</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    visibility: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">hidden</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}">.clearfix</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    *zoom: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">1</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span><span style="${ssrRenderStyle({ "color": "#7F848E", "font-style": "italic" })}">/*ie6清除浮动的方式 *号只有IE6-IE7执行，其他浏览器不执行*/</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><h2 id="使用before和after双伪元素清除浮动" tabindex="-1">使用before和after双伪元素清除浮动 ** <a class="header-anchor" href="#使用before和after双伪元素清除浮动" aria-label="Permalink to &quot;使用before和after双伪元素清除浮动 **&quot;">​</a></h2><div class="language-css line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">css</span><pre class="shiki one-dark-pro vp-code"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}">.clearfix</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}">:after</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">,</span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">.clearfix</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}">:before</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    content: </span><span style="${ssrRenderStyle({ "color": "#98C379" })}">&quot;&quot;</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    display: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">table</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}">.clearfix</span><span style="${ssrRenderStyle({ "color": "#56B6C2" })}">:after</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    clear: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">both</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#D19A66" })}">.clearfix</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">    *zoom: </span><span style="${ssrRenderStyle({ "color": "#D19A66" })}">1</span><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#ABB2BF" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("workspace/Css/clearfix.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const clearfix = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  clearfix as default
};
